"""ASR transcription backends.

This module is the actual implementation behind ``pipelines.asr``. Two
backends are supported:

- ``faster-whisper`` (default): real transcription via the
  `faster-whisper <https://github.com/SYSTRAN/faster-whisper>`_ library.
  Imported lazily so machines without it can still run ``--help`` and the
  ``dummy`` backend.
- ``dummy``: deterministic, dependency-free backend used by
  ``tools/test_asr_pipeline.py`` and by the example record. Reads the
  input file's bytes only to compute its SHA-256, then returns a single
  fake segment. Useful for exercising the descriptor / pointer plumbing
  without dragging an ML model into CI.

The :func:`transcribe` return value is the same regardless of backend so
the dispatcher and downstream pipelines (e.g. ``pipelines.text``) only
have one shape to deal with.
"""
from __future__ import annotations

import hashlib
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import List, Optional


@dataclass
class Segment:
    """A single transcribed span."""

    index: int
    start: float
    end: float
    text: str
    avg_logprob: Optional[float] = None
    no_speech_prob: Optional[float] = None


@dataclass
class TranscriptionResult:
    """Full transcript returned by :func:`transcribe`.

    The shape is intentionally conservative — every field that
    faster-whisper exposes which can be encoded as a JSON-native type is
    preserved; richer fields (word-level timestamps, language detection
    probabilities) can be added without breaking the schema by tunneling
    them through ``metadata``.
    """

    audio_path: str
    audio_sha256: str
    duration_seconds: float
    language: str
    language_confidence: Optional[float]
    backend: str
    model_id: str
    segments: List[Segment] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        d = asdict(self)
        # ``segments`` already serialises via asdict; keep field order stable.
        return d


def _sha256_of(path: Path, chunk: int = 1 << 20) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        while True:
            buf = fh.read(chunk)
            if not buf:
                break
            h.update(buf)
    return "sha256:" + h.hexdigest()


def _transcribe_dummy(
    audio_path: Path,
    model: str,
    language: Optional[str],
) -> TranscriptionResult:
    audio_hash = _sha256_of(audio_path)
    text = (
        f"[dummy backend] no real ASR was performed; this file's sha256 is "
        f"{audio_hash}."
    )
    return TranscriptionResult(
        audio_path=str(audio_path),
        audio_sha256=audio_hash,
        duration_seconds=0.0,
        language=language or "und",
        language_confidence=None,
        backend="dummy",
        model_id=f"dummy:{model}",
        segments=[
            Segment(index=0, start=0.0, end=0.0, text=text)
        ],
        metadata={"note": "Generated by the dummy backend for tests/examples."},
    )


def _transcribe_faster_whisper(
    audio_path: Path,
    model: str,
    language: Optional[str],
    device: str,
) -> TranscriptionResult:
    # Lazy import: heavy dependency, must NOT be imported when --help or the
    # dummy backend is the only thing that runs.
    from faster_whisper import WhisperModel  # type: ignore

    audio_hash = _sha256_of(audio_path)
    whisper = WhisperModel(model, device=device, compute_type="int8" if device == "cpu" else "float16")
    seg_iter, info = whisper.transcribe(str(audio_path), language=language, vad_filter=False)
    segments: List[Segment] = []
    for i, seg in enumerate(seg_iter):
        segments.append(
            Segment(
                index=i,
                start=float(seg.start),
                end=float(seg.end),
                text=seg.text.strip(),
                avg_logprob=getattr(seg, "avg_logprob", None),
                no_speech_prob=getattr(seg, "no_speech_prob", None),
            )
        )

    return TranscriptionResult(
        audio_path=str(audio_path),
        audio_sha256=audio_hash,
        duration_seconds=float(getattr(info, "duration", 0.0)),
        language=getattr(info, "language", language or "und"),
        language_confidence=getattr(info, "language_probability", None),
        backend="faster-whisper",
        model_id=f"faster-whisper:{model}",
        segments=segments,
        metadata={},
    )


def transcribe(
    audio_path: Path | str,
    model: str = "small",
    language: Optional[str] = None,
    device: str = "cpu",
    backend: str = "faster-whisper",
) -> TranscriptionResult:
    """Transcribe a single audio file with the requested backend.

    Args:
        audio_path: Path to the source audio file. Anything ffmpeg can decode
            works for the faster-whisper backend; the dummy backend doesn't
            care about the contents.
        model: Whisper model id (``tiny``, ``base``, ``small``, ``medium``,
            ``large-v3``). Ignored by the dummy backend.
        language: ISO-639-1 language hint. ``None`` enables auto-detection.
        device: ``"cpu"`` (default, offline-friendly) or ``"cuda"``.
        backend: ``"faster-whisper"`` or ``"dummy"``.

    Returns:
        A :class:`TranscriptionResult`.
    """
    p = Path(audio_path)
    if not p.exists():
        raise FileNotFoundError(f"audio file not found: {audio_path!r}")

    if backend == "dummy":
        return _transcribe_dummy(p, model, language)
    if backend == "faster-whisper":
        return _transcribe_faster_whisper(p, model, language, device)
    raise ValueError(f"unknown backend: {backend!r}")
