#!/usr/bin/env python3
"""Build the public DLRS registry artefacts.

Outputs (under ``registry/``):

- ``humans.index.jsonl`` — one record per line, machine-readable
- ``humans.index.csv``   — same data, spreadsheet-friendly
- ``index.html``         — minimal static HTML table for browsers and
                           gh-pages hosting (no JS framework, no external CSS)

This replaces the v0.4 plan to ship an interactive review console: a static
HTML page is enough for read-only auditors and forks. The interactive console
is deferred to v0.6+. See ROADMAP.md.
"""
from __future__ import annotations

import csv
import html
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / 'registry'


def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def badges(manifest):
    b = []
    review = manifest.get('review', {})
    rights = manifest.get('rights', {})
    if review.get('verified_consent_badge'):
        b.append('verified-consent')
    if review.get('public_data_only_badge'):
        b.append('public-data-only')
    if not manifest.get('rights', {}).get('allow_public_listing'):
        b.append('restricted-runtime')
    if rights.get('cross_border_transfer_status') == 'blocked' or rights.get('cross_border_transfer_basis') == 'none':
        b.append('cross-border-blocked')
    if manifest.get('subject', {}).get('status') == 'deceased':
        b.append('memorial-review-required')
    return b


def public_ok(m):
    if m.get('visibility') not in ('public_indexed', 'public_unlisted'):
        return False
    if not m.get('rights', {}).get('allow_public_listing'):
        return False
    if m.get('review', {}).get('status') != 'approved_public':
        return False
    if m.get('subject', {}).get('is_minor'):
        return False
    if not (m.get('review', {}).get('verified_consent_badge') or m.get('review', {}).get('public_data_only_badge')):
        return False
    return True


def _render_html(entries: list[dict]) -> str:
    """Render the static review page. No external resources, inline CSS only."""
    rows = []
    for e in entries:
        badges_html = ''.join(
            f'<span class="b b-{html.escape(b)}">{html.escape(b)}</span>' for b in e['badges']
        ) or '<span class="b b-none">none</span>'
        rows.append(
            '<tr>'
            f'<td><code>{html.escape(e["record_id"])}</code></td>'
            f'<td>{html.escape(e["display_name"])}</td>'
            f'<td>{html.escape(e["region"])} / {html.escape(e["locale"])}</td>'
            f'<td>{html.escape(e["visibility"])}</td>'
            f'<td>{badges_html}</td>'
            f'<td>{html.escape(e["risk_level"])}</td>'
            f'<td><time datetime="{html.escape(e["updated_at"])}">{html.escape(e["updated_at"])}</time></td>'
            f'<td><a href="../{html.escape(e["path"])}/manifest.json">manifest</a></td>'
            '</tr>'
        )
    body_rows = '\n'.join(rows) if rows else '<tr><td colspan="8"><em>No public records yet. The exclusion logic in tools/build_registry.py is intentionally strict; see docs/COMPLIANCE_CHECKLIST.md.</em></td></tr>'
    generated_at = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>DLRS Public Registry</title>
<meta name="description" content="Static index of DLRS public records. Generated by tools/build_registry.py.">
<meta name="generator" content="dlrs/build_registry">
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font: 14px/1.45 system-ui, -apple-system, "Segoe UI", sans-serif; margin: 1.5rem; max-width: 1100px; }}
  h1 {{ font-size: 1.4rem; margin-bottom: 0.25rem; }}
  p.lede {{ margin-top: 0; color: #555; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 1rem; font-size: 13px; }}
  th, td {{ padding: 6px 8px; border-bottom: 1px solid #ddd; vertical-align: top; }}
  th {{ background: #f2f3f5; text-align: left; font-weight: 600; }}
  code {{ font: 12px/1.2 ui-monospace, SFMono-Regular, Menlo, monospace; }}
  .b {{ display: inline-block; padding: 1px 6px; margin: 1px 2px; border-radius: 9px; background: #eef; color: #224; font-size: 11px; }}
  .b-verified-consent {{ background: #e0f5e9; color: #146c2e; }}
  .b-public-data-only {{ background: #eef0fa; color: #25408f; }}
  .b-restricted-runtime {{ background: #fff5e6; color: #9a5d00; }}
  .b-cross-border-blocked {{ background: #fde7e7; color: #a01818; }}
  .b-memorial-review-required {{ background: #f3e9f9; color: #5e2d7a; }}
  .b-none {{ background: #eee; color: #555; }}
  footer {{ margin-top: 1.5rem; color: #666; font-size: 12px; }}
</style>
</head>
<body>
<h1>DLRS public registry</h1>
<p class="lede">
  Read-only listing of records whose <code>visibility</code>,
  <code>review.status</code>, and either <code>verified_consent_badge</code>
  or <code>public_data_only_badge</code> all gate-pass. Generated from
  <a href="https://github.com/Digital-Life-Repository-Standard/DLRS">the DLRS reference repo</a>
  by <code>tools/build_registry.py</code>. Inclusion logic is documented in
  <a href="https://github.com/Digital-Life-Repository-Standard/DLRS/blob/master/docs/COLLECTION_STANDARD.md">docs/COLLECTION_STANDARD.md</a>
  and <a href="https://github.com/Digital-Life-Repository-Standard/DLRS/blob/master/docs/COMPLIANCE_CHECKLIST.md">docs/COMPLIANCE_CHECKLIST.md</a>.
</p>
<table>
<thead>
<tr><th>record_id</th><th>display_name</th><th>region / locale</th><th>visibility</th><th>badges</th><th>risk</th><th>last_modified_at</th><th>manifest</th></tr>
</thead>
<tbody>
{body_rows}
</tbody>
</table>
<footer>
  <p>{len(entries)} record(s). Generated {generated_at}. AI-generated outputs from records below MUST carry the disclosure declared in their <code>public_disclosure</code>.</p>
</footer>
</body>
</html>
"""


def main():
    entries = []
    for manifest_path in sorted((ROOT / 'humans').glob('*/*/*/manifest.json')):
        m = load_json(manifest_path)
        if not public_ok(m):
            continue
        rel = manifest_path.parent.relative_to(ROOT).as_posix()
        e = {
            'record_id': m['record_id'],
            'path': rel,
            'display_name': m['subject']['display_name'],
            'visibility': m['visibility'],
            'badges': badges(m),
            'region': m['subject']['residency_region'],
            'locale': m['subject']['locale'],
            'risk_level': m['review']['risk_level'],
            'updated_at': m['audit']['last_modified_at'],
        }
        entries.append(e)

    REGISTRY.mkdir(exist_ok=True)
    with open(REGISTRY / 'humans.index.jsonl', 'w', encoding='utf-8') as f:
        for e in entries:
            f.write(json.dumps(e, ensure_ascii=False) + '\n')
    with open(REGISTRY / 'humans.index.csv', 'w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=['record_id', 'path', 'display_name', 'visibility', 'badges', 'region', 'locale', 'risk_level', 'updated_at'])
        writer.writeheader()
        for e in entries:
            row = e.copy()
            row['badges'] = '|'.join(row['badges'])
            writer.writerow(row)
    (REGISTRY / 'index.html').write_text(_render_html(entries), encoding='utf-8')
    print(f'Built registry entries: {len(entries)} (jsonl, csv, html)')


if __name__ == '__main__':
    main()
